### ISSUE TITLE
Tipa todas las funciones

### ISSUE THREAD

**Issue by ZabreLight** [abrildelburgo/TierraDeBarbaros#10]
Todas las funciones inclusive las extras que usaste para delegar tienen que estar tipadas. Es necesario? No, pero te va a servir muchisimo para practicar. Ademas hace que el codigo sea mas entendible para alguien que lo tiene que leer, como digamos, un ayudante que lo tiene que corregir (hola) jajajaja

**Comment by abrildelburgo** [comment]
@ZabreLight  jajajajajakajajajajaja mil perdones
